### ISSUE TITLE
Script to download zip file - Full Replacement Monthly NPI File

### ISSUE THREAD

**Issue by eddyizm** [eddyizm/NPI_FILES#1]
URL: https://download.cms.gov/nppes/NPI_Files.html
the files are the ones at the bottom, we can split this issue into a couple. 
The first one we want to get is **Full Replacement Monthly NPI File**

**Comment by eddyizm** [comment]
Re-opening, looks like we got the deactivated file previously.

**Comment by stevenhalverson** [comment]
was it the wrong file i targeted? i have code to change the URL date it's set to 111323.  so after that date and for the rest of November it will download that file.

**Comment by eddyizm** [comment]
Let's try and use the info from the page to determine the file date, since I believe the file name stays the same. This issue is for `Full Replacement Monthly NPI File` - I believe you ended up grabbing was for deactivated npis. We will use that one too but it is not for this issue.

**Comment by eddyizm** [comment]
I will add an additional issue to unpack the zip and then load it into the db. We can delete the zip but keep the csv file.

**Comment by eddyizm** [comment]
full file downloaded
