### ISSUE TITLE
front end setup

### ISSUE THREAD

**Issue by eddyizm** [eddyizm/NPI_FILES#4]
react, vue, angular, I don't care but we want instructions on how to set up and make sure we add the correct files to the ignore file, we don't want junk in the repo, base setup as we will have to figure out what we want it to look up.

**Comment by llNovall** [comment]
If you are going to use Angular, these needs to be added to gitignore depending on the location of the project.

.angular
.vscode
[Dd]ist/

**Comment by llNovall** [comment]
I couldn't find the channel on discord for this project so I'll leave the message here. Do you want me to create the said angular project to the repository under the folder WebApp? I can also update the git-ignore and push it with relevant changes.

**Comment by eddyizm** [comment]
Yeah, I don't have a channel, except a project thread with another one, but let's start with some basic design before we push code. I will create a channel to look in there but other wise, yes I like that idea

**Comment by llNovall** [comment]
Okay, sounds good.

**Comment by eddyizm** [comment]
will work on containerizing this next.
